spring:
  kafka:
    bootstrap-servers: localhost:9093, localhost:9094
    consumer:
      group-id: notification-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
app:
  topics:
    bidEvents: bid-events.v1
    auctionEvents: auction-events.v1

server:
  port: 8085