server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auctiondb
    username: admin_db
    password: swapnilg0712
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC

  flyway:
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: player-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
app:
  topics:
    playerEvents: player-events.v1