server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auctiondb
    username: admin_db
    password: swapnilg0712
    driver-class-name: org.postgresql.Driver
#  jackson:
#    serialization:
#      FAIL_ON_EMPTY_BEANS: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC

  flyway:
    baseline-on-migrate: true

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: auction-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.example.auction_service.events
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

app:
  topics:
    bids: bid-events.v1
    auctions: auction-events.v1
