spring:
  security:
    basic:
      enabled: false
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8085
          predicates:
            - Path=/auth/**
        - id: bids-service
          uri: http://localhost:8081
          predicates:
            - Path=/bids/**
        - id: auctions-service
          uri: http://localhost:8082
          predicates:
            - Path=/auctions/**
        - id: player-service
          uri: http://localhost:8086
          predicates:
            - Path=/players/**
        - id: pool-service
          uri: http://localhost:8086
          predicates:
            - Path=/pool/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE

server:
  port: 8084

eureka:
  client:
    enabled: false
