spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: bids-service
          uri: http://localhost:8081
          predicates:
            - Path=/bids/**
        - id: auctions-service
          uri: http://localhost:8082
          predicates:
            - Path=/auctions/**
server:
  port: 8084

eureka:
  client:
    enabled: false